ci: Add job that uses git diff to see if the Cargo.toml file's version number

diff --git a/.github/workflows/lint_fmt_test.yml b/.github/workflows/lint_fmt_test.yml
--- a/.github/workflows/lint_fmt_test.yml
+++ b/.github/workflows/lint_fmt_test.yml
@@ -29,6 +29,21 @@ jobs:
         - uses: actions/checkout@v3
         - run: cargo clippy --no-deps
 
+    check-bump:
+        name: Check Version Bump
+        runs-on: ubuntu-latest
+        steps:
+        - uses: actions/checkout@v3
+        - name: Check if version needs bumped
+          run: |
+            if ! git diff Cargo.toml; then 
+                echo "ERROR You forgot to bump the version number in Cargo.toml!!!"
+                echo "ERROR     Edit the version number in Cargo.toml, and then make a `chore:` commit and push it to fix this."
+                echo "ERROR     Make sure you follow SemVer 2.0 when bumping the version number."
+                exit 1
+                # Note: This is very rudimentary check, but it is better than nothing.
+            fi
+
     test:
         name: Test
         runs-on: ubuntu-latest
